<?php
namespace Webdevvie\Epp\Tests;

use PHPUnit\Framework\TestCase;

/**
 *
 */
class SerializeTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
    
}